# Project-wide Gradle settings.
# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html

# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for tweaking memory settings.
org.gradle.jvmargs=-Xmx3072m -Dfile.encoding=UTF-8
kotlin.compiler.execution.strategy=in-process

# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects. More details, visit
# http://www.gradle.org/docs/current/userguide/multi_project_builds.html#sec:decoupled_projects
org.gradle.parallel=true

# AndroidX enables the use of libraries from the Jetpack family.
android.useAndroidX=true
# Automatically convert third-party libraries to use AndroidX.
android.enableJetifier=true

# Force Gradle to use the Java version from Android Studio
org.gradle.java.home=C:\\Program Files\\Android\\Android Studio\\jbr

# Suppress compileSdk 34 warning
android.suppressUnsupportedCompileSdk=34
